apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depl
  namespace: k8s-program
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          resources:
            requests:
              memory: 512Mi
              cpu: 0.1
            limits:
              memory: 1Gi
              cpu: 0.2
          volumeMounts:
            - name: mongo-storage
              mountPath: ../data/mongo
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
              
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: k8s-program
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    app: mongo