apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
  namespace: k8s-program
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: posts-ms
  template:
    metadata:
      name: posts-ms
      labels:
        app: posts-ms
    spec:
      containers:
        - name: posts-ms
          image: hakobhn/dockerdemo-posts:1.0.1
          resources:
            requests:
              memory: 512Mi
              cpu: 0.1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: posts-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 20
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
            timeoutSeconds: 15
            periodSeconds: 20
            failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  name: posts-ms
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: posts-ms
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30081