apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
  namespace: k8s-program
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      name: users-ms
      labels:
        app: users-ms
    spec:
      containers:
        - name: users-ms
          image: hakobhn/dockerdemo-users:1.0.1
          resources:
            requests:
              memory: 512Mi
              cpu: 0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: users-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 20
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 15
            periodSeconds: 20
            failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  name: users-ms
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: users-ms
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080