apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts-ms
  template:
    metadata:
      name: posts-ms
      labels:
        app: posts-ms
    spec:
      containers:
        - name: posts-ms
          image: hakobhn/dockerdemo-posts:1.0.0
          resources:
            requests:
              memory: 512Mi
              cpu: 0.1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/dockerdemo
            - name: USERS_MS_BASE_URI
              value: http://users-ms:8080

---

apiVersion: v1
kind: Service
metadata:
  name: posts-ms
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: posts-ms
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30081