apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      name: users-ms
      labels:
        app: users-ms
    spec:
      containers:
        - name: users-ms
          image: hakobhn/dockerdemo-users:1.0.0
          resources:
            requests:
              memory: 512Mi
              cpu: 0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/dockerdemo
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password

---

apiVersion: v1
kind: Service
metadata:
  name: users-ms
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: users-ms
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080