apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
  namespace: k8s-program
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users
    (
      id serial not null primary key,
      username character varying(255) NOT NULL,
      number_of_posts integer NOT NULL,
      created_at timestamp without time zone,
      updated_at timestamp without time zone NOT NULL,
      CONSTRAINT uk_username UNIQUE (username)
    );